# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

dist: trusty

# list any PHP version you want to test against
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - travis_wait 20 composer self-update
  - travis_wait 20 composer install --prefer-source --no-interaction --dev

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v